# Generated by Django 5.0.14 on 2026-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_x_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
