# Generated by Django 5.0.14 on 2026-04-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_profile_twitter_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.show'),
        ),
    ]
