# Generated by Django 6.0.2 on 2026-02-20 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_mediaasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('tech-support', 'Technical Support'), ('media-inquiry', 'Media Collaboration')], default='general', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_responded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='hudl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='maxpreps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='role',
            field=models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach')], default='athlete', max_length=10),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_votes', to='members.profile')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('voter', 'athlete')},
            },
        ),
    ]
