# Generated by Django 6.0.2 on 2026-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_contactinquiry_remove_guestrequest_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the guest or show poster', null=True, upload_to='show_guests/'),
        ),
    ]
