# Generated by Django 6.0.2 on 2026-02-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_show_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True, help_text='Description or caption for the media'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('highlight', 'Game Highlight'), ('interview', 'Interview'), ('training', 'Training Footage')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Custom thumbnail image (optional)', null=True, upload_to='media_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(help_text='Video file (MP4, MOV, etc.)', upload_to='athlete_media/'),
        ),
    ]
