# Generated by Django 5.0.14 on 2026-03-17 02:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_mediaasset_options_mediaasset_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this platform', max_length=100)),
                ('platform_type', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('owncast', 'Owncast'), ('custom', 'Custom RTMP')], default='youtube', max_length=20)),
                ('rtmp_url', models.CharField(help_text='RTMP server URL (e.g., rtmp://a.rtmp.youtube.com/live2)', max_length=500)),
                ('stream_key', models.CharField(help_text='Stream key/secret for this platform', max_length=500)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable streaming to this platform')),
                ('is_active', models.BooleanField(default=False, help_text='Currently streaming to this platform')),
                ('last_test', models.DateTimeField(blank=True, help_text='Last connection test timestamp', null=True)),
                ('test_status', models.BooleanField(default=False, help_text='Last test result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_broadcast_id', models.CharField(blank=True, help_text='YouTube broadcast ID (optional)', max_length=100)),
                ('facebook_page_id', models.CharField(blank=True, help_text='Facebook page ID (optional)', max_length=100)),
                ('tiktok_username', models.CharField(blank=True, help_text='TikTok username (optional)', max_length=100)),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Custom platform settings')),
            ],
            options={
                'ordering': ['platform_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StreamingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('viewer_count', models.IntegerField(default=0, help_text='Current viewer count')),
                ('bitrate', models.IntegerField(default=0, help_text='Current bitrate in kbps')),
                ('is_active', models.BooleanField(default=True, help_text='Session is currently active')),
                ('total_viewers', models.IntegerField(default=0, help_text='Total viewers across session')),
                ('peak_viewers', models.IntegerField(default=0, help_text='Peak concurrent viewers')),
                ('total_duration', models.IntegerField(default=0, help_text='Total duration in seconds')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(help_text='Unique participant identifier', max_length=100)),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest'), ('viewer', 'Viewer')], default='guest', max_length=20)),
                ('display_name', models.CharField(help_text='Display name in room', max_length=200)),
                ('peer_id', models.CharField(blank=True, help_text='WebRTC peer ID', max_length=500)),
                ('stream_key', models.CharField(blank=True, help_text='Stream key for this participant', max_length=200)),
                ('ice_servers', models.JSONField(blank=True, default=list, help_text='ICE servers configuration')),
                ('is_connected', models.BooleanField(default=False, help_text='Currently connected')),
                ('has_audio', models.BooleanField(default=True, help_text='Audio enabled')),
                ('has_video', models.BooleanField(default=True, help_text='Video enabled')),
                ('is_screen_sharing', models.BooleanField(default=False, help_text='Screen sharing')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('connection_quality', models.IntegerField(default=100, help_text='Connection quality (0-100)')),
                ('bitrate', models.IntegerField(default=0, help_text='Current bitrate in kbps')),
                ('packet_loss', models.FloatField(default=0.0, help_text='Packet loss percentage')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(help_text='Unique room identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Room display name', max_length=200)),
                ('room_type', models.CharField(choices=[('interview', 'Interview'), ('training', 'Training'), ('analysis', 'Game Analysis'), ('coaching', 'Coaching')], default='interview', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Room description')),
                ('host_stream_key', models.CharField(blank=True, help_text="Host's stream key for OBS virtual camera", max_length=200)),
                ('guest_name', models.CharField(blank=True, help_text='Guest name', max_length=200)),
                ('guest_email', models.EmailField(blank=True, help_text='Guest email', max_length=254)),
                ('guest_stream_key', models.CharField(blank=True, help_text="Guest's stream key for WebRTC connection", max_length=200)),
                ('is_public', models.BooleanField(default=False, help_text='Publicly accessible room')),
                ('requires_password', models.BooleanField(default=False, help_text='Requires password to join')),
                ('room_password', models.CharField(blank=True, help_text='Room password', max_length=100)),
                ('max_participants', models.IntegerField(default=2, help_text='Maximum participants (host + guests)')),
                ('is_active', models.BooleanField(default=True, help_text='Room is active')),
                ('is_live', models.BooleanField(default=False, help_text='Room is currently live streaming')),
                ('is_recording', models.BooleanField(default=False, help_text='Room is being recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='Scheduled start time', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='End time', null=True)),
                ('rtmp_output_url', models.CharField(blank=True, help_text='RTMP output URL for streaming', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional room metadata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE Candidate'), ('join', 'Join'), ('leave', 'Leave'), ('error', 'Error')], max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Signal payload (SDP, candidate, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False, help_text='Signal was delivered')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-air_date']},
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('training', 'Training'), ('analysis', 'Game Analysis'), ('recruiting', 'Recruiting'), ('coaching', 'Coaching'), ('other', 'Other')], default='interview', max_length=50),
        ),
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed show description'),
        ),
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='show',
            name='guest_name_override',
            field=models.CharField(blank=True, help_text='Override guest name if not in system', max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Show in public calendar'),
        ),
        migrations.AddField(
            model_name='show',
            name='show_notes',
            field=models.TextField(blank=True, help_text='Additional notes, resources, or links'),
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., football, recruiting, training)', max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for calendar/past shows (optional)', null=True, upload_to='show_thumbnails/'),
        ),
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Link to guest profile (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.profile'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, help_text='Main show image/poster', null=True, upload_to='show_images/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Currently broadcasting live'),
        ),
        migrations.AlterField(
            model_name='show',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full show transcript'),
        ),
        migrations.AlterField(
            model_name='show',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to recorded video (YouTube, Facebook, etc.)'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['-air_date', 'is_published'], name='members_sho_air_dat_b506da_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['guest', 'is_published'], name='members_sho_guest_i_88b48f_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['category', 'is_published'], name='members_sho_categor_000545_idx'),
        ),
        migrations.AddField(
            model_name='streamingsession',
            name='platforms',
            field=models.ManyToManyField(blank=True, help_text='Platforms streamed to in this session', to='members.streamingplatform'),
        ),
        migrations.AddField(
            model_name='webrtcparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webrtcroom',
            name='host',
            field=models.ForeignKey(help_text='Room host/creator', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webrtcroom',
            name='streaming_session',
            field=models.ForeignKey(blank=True, help_text='Associated streaming session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.streamingsession'),
        ),
        migrations.AddField(
            model_name='webrtcparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='members.webrtcroom'),
        ),
        migrations.AddField(
            model_name='webrtcsignal',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='members.webrtcparticipant'),
        ),
        migrations.AddField(
            model_name='webrtcsignal',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='members.webrtcroom'),
        ),
        migrations.AddField(
            model_name='webrtcsignal',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to='members.webrtcparticipant'),
        ),
        migrations.AddIndex(
            model_name='webrtcroom',
            index=models.Index(fields=['room_id', 'is_active'], name='members_web_room_id_f55703_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcroom',
            index=models.Index(fields=['host', 'is_active'], name='members_web_host_id_865342_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcroom',
            index=models.Index(fields=['is_live', 'is_active'], name='members_web_is_live_0efeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcparticipant',
            index=models.Index(fields=['room', 'is_connected'], name='members_web_room_id_7b2105_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcparticipant',
            index=models.Index(fields=['participant_id', 'is_connected'], name='members_web_partici_c7eaaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webrtcparticipant',
            unique_together={('room', 'participant_id')},
        ),
        migrations.AddIndex(
            model_name='webrtcsignal',
            index=models.Index(fields=['room', 'signal_type', 'created_at'], name='members_web_room_id_a81b31_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcsignal',
            index=models.Index(fields=['sender', 'receiver', 'delivered'], name='members_web_sender__0bf36e_idx'),
        ),
    ]
