# Generated by Django 5.0.14 on 2026-03-13 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_streamingplatform_streamingsession_webrtcparticipant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-air_date']},
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.CharField(blank=True, choices=[('interview', 'Interview'), ('training', 'Training'), ('analysis', 'Game Analysis'), ('recruiting', 'Recruiting'), ('coaching', 'Coaching'), ('other', 'Other')], default='interview', max_length=50),
        ),
        migrations.AddField(
            model_name='show',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed show description'),
        ),
        migrations.AddField(
            model_name='show',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='show',
            name='guest_name_override',
            field=models.CharField(blank=True, help_text='Override guest name if not in system', max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Show in public calendar'),
        ),
        migrations.AddField(
            model_name='show',
            name='show_notes',
            field=models.TextField(blank=True, help_text='Additional notes, resources, or links'),
        ),
        migrations.AddField(
            model_name='show',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., football, recruiting, training)', max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for calendar/past shows (optional)', null=True, upload_to='show_thumbnails/'),
        ),
        migrations.AddField(
            model_name='show',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Link to guest profile (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.profile'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, help_text='Main show image/poster', null=True, upload_to='show_images/'),
        ),
        migrations.AlterField(
            model_name='show',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Currently broadcasting live'),
        ),
        migrations.AlterField(
            model_name='show',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full show transcript'),
        ),
        migrations.AlterField(
            model_name='show',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to recorded video (YouTube, Facebook, etc.)'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['-air_date', 'is_published'], name='members_sho_air_dat_b506da_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['guest', 'is_published'], name='members_sho_guest_i_88b48f_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['category', 'is_published'], name='members_sho_categor_000545_idx'),
        ),
    ]
