# Generated by Django 5.0.14 on 2026-03-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_show_options_show_category_show_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(help_text='Unique room identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Room display name', max_length=200)),
                ('room_type', models.CharField(choices=[('interview', 'Interview'), ('training', 'Training'), ('analysis', 'Game Analysis'), ('coaching', 'Coaching')], default='interview', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Room description')),
                ('host_stream_key', models.CharField(blank=True, help_text="Host's stream key for OBS virtual camera", max_length=200)),
                ('guest_name', models.CharField(blank=True, help_text='Guest name', max_length=200)),
                ('guest_email', models.EmailField(blank=True, help_text='Guest email', max_length=254)),
                ('guest_stream_key', models.CharField(blank=True, help_text="Guest's stream key for WebRTC connection", max_length=200)),
                ('is_public', models.BooleanField(default=False, help_text='Publicly accessible room')),
                ('requires_password', models.BooleanField(default=False, help_text='Requires password to join')),
                ('room_password', models.CharField(blank=True, help_text='Room password', max_length=100)),
                ('max_participants', models.IntegerField(default=2, help_text='Maximum participants (host + guests)')),
                ('is_active', models.BooleanField(default=True, help_text='Room is active')),
                ('is_live', models.BooleanField(default=False, help_text='Room is currently live streaming')),
                ('is_recording', models.BooleanField(default=False, help_text='Room is being recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='Scheduled start time', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='End time', null=True)),
                ('rtmp_output_url', models.CharField(blank=True, help_text='RTMP output URL for streaming', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional room metadata')),
                ('host', models.ForeignKey(help_text='Room host/creator', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('streaming_session', models.ForeignKey(blank=True, help_text='Associated streaming session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.streamingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(help_text='Unique participant identifier', max_length=100)),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest'), ('viewer', 'Viewer')], default='guest', max_length=20)),
                ('display_name', models.CharField(help_text='Display name in room', max_length=200)),
                ('peer_id', models.CharField(blank=True, help_text='WebRTC peer ID', max_length=500)),
                ('stream_key', models.CharField(blank=True, help_text='Stream key for this participant', max_length=200)),
                ('ice_servers', models.JSONField(blank=True, default=list, help_text='ICE servers configuration')),
                ('is_connected', models.BooleanField(default=False, help_text='Currently connected')),
                ('has_audio', models.BooleanField(default=True, help_text='Audio enabled')),
                ('has_video', models.BooleanField(default=True, help_text='Video enabled')),
                ('is_screen_sharing', models.BooleanField(default=False, help_text='Screen sharing')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('connection_quality', models.IntegerField(default=100, help_text='Connection quality (0-100)')),
                ('bitrate', models.IntegerField(default=0, help_text='Current bitrate in kbps')),
                ('packet_loss', models.FloatField(default=0.0, help_text='Packet loss percentage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='members.webrtcroom')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRTCSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE Candidate'), ('join', 'Join'), ('leave', 'Leave'), ('error', 'Error')], max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Signal payload (SDP, candidate, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False, help_text='Signal was delivered')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='members.webrtcparticipant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='members.webrtcroom')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to='members.webrtcparticipant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webrtcroom',
            index=models.Index(fields=['room_id', 'is_active'], name='members_web_room_id_f55703_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcroom',
            index=models.Index(fields=['host', 'is_active'], name='members_web_host_id_865342_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcroom',
            index=models.Index(fields=['is_live', 'is_active'], name='members_web_is_live_0efeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcparticipant',
            index=models.Index(fields=['room', 'is_connected'], name='members_web_room_id_7b2105_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcparticipant',
            index=models.Index(fields=['participant_id', 'is_connected'], name='members_web_partici_c7eaaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webrtcparticipant',
            unique_together={('room', 'participant_id')},
        ),
        migrations.AddIndex(
            model_name='webrtcsignal',
            index=models.Index(fields=['room', 'signal_type', 'created_at'], name='members_web_room_id_a81b31_idx'),
        ),
        migrations.AddIndex(
            model_name='webrtcsignal',
            index=models.Index(fields=['sender', 'receiver', 'delivered'], name='members_web_sender__0bf36e_idx'),
        ),
    ]
