# Generated by Django 5.0.14 on 2026-04-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_webrtcroom_webrtcparticipant_webrtcsignal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrtcparticipant',
            name='egress_bitrate',
            field=models.IntegerField(default=2500, help_text='Bitrate for RTMP egress in kbps'),
        ),
        migrations.AddField(
            model_name='webrtcparticipant',
            name='egress_framerate',
            field=models.IntegerField(default=30, help_text='Framerate for RTMP egress'),
        ),
        migrations.AddField(
            model_name='webrtcparticipant',
            name='egress_key',
            field=models.CharField(blank=True, help_text='RTMP egress key for OBS media source', max_length=200),
        ),
        migrations.AddField(
            model_name='webrtcparticipant',
            name='egress_resolution_height',
            field=models.IntegerField(default=720, help_text='Height for RTMP egress'),
        ),
        migrations.AddField(
            model_name='webrtcparticipant',
            name='egress_resolution_width',
            field=models.IntegerField(default=1280, help_text='Width for RTMP egress'),
        ),
    ]
