# Generated by Django 5.0.14 on 2026-04-12 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_webrtcparticipant_egress_bitrate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestrequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address at time of submission', null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this request', null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for verification', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent', null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('verified', 'Email Verified - Pending Approval')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='guestrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='members_gue_status_747f05_idx'),
        ),
        migrations.AddIndex(
            model_name='guestrequest',
            index=models.Index(fields=['email', 'status'], name='members_gue_email_c936d3_idx'),
        ),
        migrations.AddIndex(
            model_name='guestrequest',
            index=models.Index(fields=['verification_token'], name='members_gue_verific_d08237_idx'),
        ),
    ]
