# Generated by Django 5.0.14 on 2026-04-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_guestrequest_options_guestrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (legacy field)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for guest request', null=True),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='show',
            field=models.ForeignKey(blank=True, help_text='Associated show', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.show'),
        ),
    ]
