# Generated by Django 5.0.14 on 2026-04-23 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_guestrequest_phone_number_guestrequest_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from title)', max_length=300, unique=True)),
                ('content', models.TextField(help_text='Blog post content (HTML supported)')),
                ('excerpt', models.TextField(blank=True, help_text='Short preview/summary of the post', max_length=500)),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the blog post (auto-compressed to WebP)', null=True, upload_to='blog_images/')),
                ('featured_image_compressed', models.ImageField(blank=True, help_text='Compressed WebP version of featured image', null=True, upload_to='blog_images/compressed/')),
                ('video_url', models.URLField(blank=True, help_text='Optional video link (YouTube, Vimeo, etc.)', max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Post category (e.g., News, Story, Update)', max_length=100)),
                ('is_published', models.BooleanField(default=False, help_text='Visible to the public')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post was published', null=True)),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow comments on this post')),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content', max_length=2000)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by admin for public display')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_comments', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='members.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_at', 'is_published'], name='members_blo_publish_cb161a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='members_blo_slug_67c96a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', '-created_at'], name='members_blo_author__60de9c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['post', 'is_approved', 'created_at'], name='members_blo_post_id_fe6d90_idx'),
        ),
        migrations.AddIndex(
            model_name='blogcomment',
            index=models.Index(fields=['author', '-created_at'], name='members_blo_author__2203ce_idx'),
        ),
    ]
