# Generated by Django 5.0.14 on 2026-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_blogpost_blogcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on the front page as featured story'),
        ),
    ]
