# Generated by Django 5.0.14 on 2026-04-23 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_blogpost_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('coach', 'Coach'), ('athlete', 'Athlete'), ('staff', 'Staff'), ('vip', 'VIP')], default='athlete', max_length=10),
        ),
    ]
