# Generated by Django 5.0.14 on 2026-04-24 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_blogpost_likes_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this post', related_name='liked_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_x_link',
            field=models.URLField(blank=True, help_text='Link to your X (Twitter) profile', max_length=255, null=True),
        ),
    ]
