# Generated by Django 5.0.14 on 2026-05-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_blogpost_likes_alter_profile_twitter_x_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingplatform',
            name='instagram_account_id',
            field=models.CharField(blank=True, help_text='Instagram account ID (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='guestrequest',
            name='role',
            field=models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach'), ('other', 'Other')], default='athlete', max_length=10),
        ),
        migrations.AlterField(
            model_name='streamingplatform',
            name='platform_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram Live'), ('tiktok', 'TikTok'), ('owncast', 'Owncast'), ('custom', 'Custom RTMP')], default='youtube', max_length=20),
        ),
    ]
