# Generated by Django 5.0.14 on 2026-05-11 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_mediaasset_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon identifier', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='forty_yard_time',
            field=models.FloatField(blank=True, help_text='40-yard dash time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.FloatField(blank=True, help_text='Grade point average (0.0 - 4.0)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_ft',
            field=models.IntegerField(blank=True, help_text='Height in feet', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_in',
            field=models.IntegerField(blank=True, help_text='Height in inches (0-11)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_bench_lbs',
            field=models.IntegerField(blank=True, help_text='Max bench press in pounds', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_power_clean_lbs',
            field=models.IntegerField(blank=True, help_text='Max power clean in pounds', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_squat_lbs',
            field=models.IntegerField(blank=True, help_text='Max squat in pounds', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shuttle_time',
            field=models.FloatField(blank=True, help_text='Pro-agility shuttle time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, help_text='Two-letter state code (e.g., TX, CA)', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='vertical_jump_in',
            field=models.FloatField(blank=True, help_text='Vertical jump in inches', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_lbs',
            field=models.IntegerField(blank=True, help_text='Weight in pounds', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sports',
            field=models.ManyToManyField(blank=True, help_text='Sports this athlete plays', to='members.sport'),
        ),
        migrations.CreateModel(
            name='StatVerificationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('vertical_jump', 'Vertical Jump'), ('forty_yard', '40-Yard Dash'), ('max_bench', 'Max Bench Press'), ('max_squat', 'Max Squat'), ('max_power_clean', 'Max Power Clean'), ('shuttle', 'Shuttle Time')], max_length=20)),
                ('video', models.FileField(help_text='Verification video file', upload_to='stat_verifications/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='stat_verification_thumbnails/')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by staff/admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_videos', to='members.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteStatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('height', 'Height'), ('weight', 'Weight'), ('vertical_jump', 'Vertical Jump'), ('forty_yard', '40-Yard Dash'), ('max_bench', 'Max Bench Press'), ('max_squat', 'Max Squat'), ('max_power_clean', 'Max Power Clean'), ('shuttle', 'Shuttle Time'), ('gpa', 'GPA')], max_length=20)),
                ('value', models.FloatField(help_text='Numeric value of the stat at this point in time')),
                ('is_verified', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_entries', to='members.profile')),
            ],
            options={
                'verbose_name': 'Athlete Stat Entry',
                'verbose_name_plural': 'Athlete Stat Entries',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['athlete', 'stat_type', '-recorded_at'], name='members_ath_athlete_38b7f3_idx'), models.Index(fields=['stat_type', 'value'], name='members_ath_stat_ty_363f1a_idx')],
            },
        ),
    ]
