# Generated by Django 5.0.14 on 2026-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_sport_profile_forty_yard_time_profile_gpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When verification email was sent', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email has been verified'),
        ),
    ]
