# Generated by Django 5.0.14 on 2026-05-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_add_email_verification'),
    ]

    operations = [
        # Fix existing NULL email_verified values (before PostgreSQL enforces NOT NULL)
        migrations.RunSQL(
            sql="UPDATE members_profile SET email_verified = FALSE WHERE email_verified IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
