# Generated by Django 5.0.14 on 2026-05-12 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_fix_null_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='sport',
            field=models.ForeignKey(blank=True, help_text='Sport this media relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.sport'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., footwork, speed, agility)', max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of views'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Coaching certifications (comma-separated)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified_coach',
            field=models.BooleanField(default=False, help_text='Coach is verified by staff'),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of coaching experience', null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('highlight', 'Game Highlight'), ('interview', 'Interview'), ('drill', 'Coach Drill/Training'), ('training', 'Training Footage')], default='video', max_length=20),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type', '-created_at'], name='members_med_media_t_4e0205_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['sport', '-created_at'], name='members_med_sport_i_a47875_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['-view_count'], name='members_med_view_co_069131_idx'),
        ),
    ]
