# Generated by Django 5.0.14 on 2026-05-15 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_coach_drill_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='is_receipt',
            field=models.BooleanField(default=False, help_text='This video is a stat/achievement receipt'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='receipt_label',
            field=models.CharField(blank=True, help_text="What stat or achievement this receipt shows (e.g., '36in vertical jump, hand-timed')", max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='sport_specific_stats',
            field=models.JSONField(blank=True, default=dict, help_text="Per-sport stats keyed by sport slug. e.g., {'basketball': {'wingspan_in': 82, 'hand_size_in': 9.5}}"),
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Drill description and instructions')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('equipment', models.CharField(blank=True, help_text='Required equipment (comma-separated)', max_length=500)),
                ('duration_minutes', models.IntegerField(default=10, help_text='Estimated duration in minutes')),
                ('reps_sets', models.CharField(blank=True, help_text="Sets/reps recommendations e.g., '3x10'", max_length=200)),
                ('skills_focused', models.CharField(blank=True, help_text='Skills this drill develops (comma-separated)', max_length=500)),
                ('view_count', models.IntegerField(default=0, help_text='Number of views')),
                ('save_count', models.IntegerField(default=0, help_text='Number of athletes who saved this drill')),
                ('is_published', models.BooleanField(default=True, help_text='Visible to the public')),
                ('is_featured', models.BooleanField(default=False, help_text='Showcased on drill library homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_drills', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_drills', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_drills', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.sport')),
                ('video', models.ForeignKey(blank=True, help_text='Video demonstration of the drill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.mediaasset')),
            ],
            options={
                'verbose_name': 'Drill',
                'verbose_name_plural': 'Drills',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['sport', '-created_at'], name='members_dri_sport_i_57fa50_idx'), models.Index(fields=['difficulty', '-created_at'], name='members_dri_difficu_3d6fec_idx'), models.Index(fields=['-view_count'], name='members_dri_view_co_8ade7f_idx'), models.Index(fields=['creator', '-created_at'], name='members_dri_creator_6de90e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_label', models.CharField(help_text="What stat they want verified (e.g., 'Bench Press 225lbs x 15')", max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the verification session')),
                ('preferred_time', models.DateTimeField(blank=True, help_text="Athlete's preferred time", null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Confirmed time slot', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('verified_value', models.FloatField(blank=True, help_text='The confirmed value witnessed live', null=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Staff notes from the verification session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='members.profile')),
                ('result_video', models.ForeignKey(blank=True, help_text='The recorded verification video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.statverificationvideo')),
                ('room', models.ForeignKey(blank=True, help_text='LiveKit room for the verification session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.webrtcroom')),
            ],
            options={
                'verbose_name': 'Live Verification Request',
                'verbose_name_plural': 'Live Verification Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['athlete', 'status'], name='members_liv_athlete_5e5bde_idx'), models.Index(fields=['status', 'scheduled_at'], name='members_liv_status_30ae14_idx'), models.Index(fields=['assigned_staff', 'status'], name='members_liv_assigne_75d10f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Tag key e.g., 'wingspan', 'skill', 'technique'", max_length=100)),
                ('value', models.CharField(help_text="Tag value e.g., '82in', 'footwork', 'release speed'", max_length=200)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tags', to='members.mediaasset')),
            ],
            options={
                'verbose_name': 'Media Tag',
                'verbose_name_plural': 'Media Tags',
                'indexes': [models.Index(fields=['key', 'value'], name='members_med_key_3594a1_idx'), models.Index(fields=['media', 'key'], name='members_med_media_i_0bba22_idx')],
            },
        ),
        migrations.CreateModel(
            name='SportAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Wingspan, Arm Length, Exit Velocity', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('unit', models.CharField(blank=True, help_text='e.g., inches, seconds, mph, feet', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji indicator', max_length=10)),
                ('description', models.TextField(blank=True, help_text='What recruiters look for in this attribute')),
                ('is_measurable', models.BooleanField(default=True, help_text='True = numeric field, False = checkbox/skill tag')),
                ('benchmark_text', models.CharField(blank=True, help_text="e.g., 'Elite: 7ft+ wingspan'", max_length=200)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within sport')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='members.sport')),
            ],
            options={
                'verbose_name': 'Sport Attribute',
                'verbose_name_plural': 'Sport Attributes',
                'ordering': ['sport', 'sort_order'],
                'unique_together': {('sport', 'slug')},
            },
        ),
    ]
