# Generated by Django 5.0.14 on 2026-05-17 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_seed_sport_attributes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth (collected only at registration)", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_parental_consent_granted',
            field=models.BooleanField(default=False, help_text='Parental consent has been obtained (COPPA)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent/guardian email for under-13 users', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='parental_consent_expires_at',
            field=models.DateTimeField(blank=True, help_text='When parental consent expires (annually)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parental_consent_granted_at',
            field=models.DateTimeField(blank=True, help_text='When parental consent was granted', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='parental_consent_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card Authorization'), ('signed_form', 'Signed Consent Form'), ('video_chat', 'Video Chat Verification')], help_text='Method used to verify parental consent', max_length=50),
        ),
        migrations.CreateModel(
            name='COPPAAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('credit_card', 'Credit Card Authorization'), ('signed_form', 'Signed Consent Form'), ('video_chat', 'Video Chat Verification'), ('age_gate_denied', 'Age Gate - Registration Denied (Under 13)'), ('age_gate_allowed', 'Age Gate - Registration Allowed (13+)'), ('consent_revoked', 'Parental Consent Revoked')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_email_hash', models.CharField(blank=True, help_text='SHA-256 hash of parent email for lookup — never store raw', max_length=64)),
                ('requester_identifier', models.CharField(blank=True, help_text='Hashed identifier for the requesting user (username hash)', max_length=64)),
                ('notes', models.TextField(blank=True, help_text="Event notes — e.g., 'Video chat verified by staff jdoe' — no PII")),
                ('staff_username', models.CharField(blank=True, help_text='Staff member who completed the verification (if applicable)', max_length=150)),
            ],
            options={
                'verbose_name': 'COPPA Audit Log Entry',
                'verbose_name_plural': 'COPPA Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='members_cop_event_t_ef9721_idx'), models.Index(fields=['-timestamp'], name='members_cop_timesta_debf44_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('underage', 'User May Be Under 13'), ('harassment', 'Harassment or Bullying'), ('non_athletic', 'Non-Athletic Content'), ('profanity', 'Profanity or Explicit Language'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about the report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed - No Action'), ('actioned', 'Reviewed - Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('moderation_notes', models.TextField(blank=True, help_text='Staff notes about the resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='members.mediaasset')),
                ('reported_user', models.ForeignKey(blank=True, help_text='User being reported (if not media-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Report',
                'verbose_name_plural': 'Content Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='members_con_status_a26926_idx'), models.Index(fields=['reporter', '-created_at'], name='members_con_reporte_ad4312_idx'), models.Index(fields=['media', 'status'], name='members_con_media_i_36861d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentalConsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_email', models.EmailField(help_text="The minor's email address", max_length=254)),
                ('parent_email', models.EmailField(help_text='Parent/guardian email address', max_length=254)),
                ('child_dob', models.DateField(help_text="Child's date of birth (used only for age verification)")),
                ('child_name', models.CharField(blank=True, help_text="Child's name (only collected if consent given)", max_length=200)),
                ('parent_name', models.CharField(blank=True, help_text='Parent/guardian full name', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Parent Response'), ('consent_given', 'Consent Granted'), ('expired', 'Expired'), ('revoked', 'Revoked by Parent')], default='pending', max_length=20)),
                ('consent_token', models.CharField(help_text='Secret token for consent URL', max_length=100, unique=True)),
                ('consent_method', models.CharField(choices=[('credit_card', 'Credit Card Authorization'), ('signed_form', 'Signed Consent Form'), ('video_chat', 'Video Chat Verification')], default='video_chat', max_length=50)),
                ('expires_at', models.DateTimeField(help_text='When this consent request expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_consent_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parental Consent Request',
                'verbose_name_plural': 'Parental Consent Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consent_token'], name='members_par_consent_61cbd8_idx'), models.Index(fields=['parent_email', 'status'], name='members_par_parent__517f7b_idx'), models.Index(fields=['status', 'expires_at'], name='members_par_status_bbb6be_idx')],
            },
        ),
    ]
