# Generated by Django 5.0.14 on 2026-05-17 05:39

import django.db.models.deletion
import django.utils.timezone
import members.ai_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_coppa_age_gate_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coach', 'Coach Assistant'), ('athlete', 'Athlete Assistant')], help_text='Which role this personality applies to', max_length=20, unique=True)),
                ('system_prompt', models.TextField(help_text="The system prompt that defines this AI's personality, knowledge, and behavior")),
                ('model_name', models.CharField(default='deepseek-chat', help_text='DeepSeek model to use (e.g., deepseek-chat, deepseek-reasoner)', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Response creativity (0.0 = deterministic, 1.0 = creative)')),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum tokens per response')),
                ('top_p', models.FloatField(default=0.95, help_text='Nucleus sampling parameter')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this AI personality')),
                ('supports_streaming', models.BooleanField(default=True, help_text='Enable streaming responses')),
                ('supports_audio_input', models.BooleanField(default=False, help_text='Enable voice input (Phase 2)')),
                ('supports_audio_output', models.BooleanField(default=False, help_text='Enable TTS output (Phase 2)')),
                ('daily_message_limit', models.IntegerField(default=50, help_text='Max messages per user per day')),
                ('rate_limit_window', models.IntegerField(default=60, help_text='Rate limit window in seconds between messages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Personality',
                'verbose_name_plural': 'AI Personalities',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coach', 'Coach Assistant'), ('athlete', 'Athlete Assistant')], help_text='Which AI assistant this session is for', max_length=20)),
                ('title', models.CharField(blank=True, help_text="Auto-generated session title (e.g., 'Offensive Line Drills Week 4')", max_length=300)),
                ('summary', members.ai_models.CompressedTextField(blank=True, help_text='Compressed summary of the conversation for context restoration')),
                ('message_count', models.IntegerField(default=0, help_text='Total messages in this session')),
                ('total_tokens', models.IntegerField(default=0, help_text='Approximate total tokens used in this session')),
                ('is_active', models.BooleanField(default=True, help_text='Session is active (can still send messages)')),
                ('is_favorited', models.BooleanField(default=False, help_text='User has favorited/bookmarked this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System Instruction'), ('user', 'User'), ('assistant', 'AI Assistant')], max_length=20)),
                ('content', members.ai_models.CompressedTextField(help_text='Message content (zlib-compressed in DB)')),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count for this message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata JSON (e.g., model params, latency)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='members.aichatsession')),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['user', '-last_message_at'], name='members_aic_user_id_eb4bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['user', 'role', '-last_message_at'], name='members_aic_user_id_a34834_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['user', 'is_active', '-last_message_at'], name='members_aic_user_id_bbde7d_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['session', 'created_at'], name='members_aic_session_9a7afd_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['session', 'role', 'created_at'], name='members_aic_session_daed25_idx'),
        ),
    ]
