# Generated by Django 5.0.14 on 2026-07-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_aipersonality_aichatsession_aichatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenRoomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default="You are a friendly, warm assistant named 'Lil' Dawg' who helps guests feel comfortable before going live on a broadcast. Your job is to:\n1. Greet them warmly by name\n2. Remind them to use headphones for clear audio\n3. Remind them to have a stable internet connection\n4. Remind them to find a quiet, well-lit space\n5. Answer any questions they have about the show\n6. Let them know they can proceed when ready\nBe concise, friendly, and encouraging. Keep responses under 3 sentences.", help_text="The system prompt that defines the avatar's personality and behavior")),
                ('guest_name', models.CharField(blank=True, help_text="Override: guest's name for the avatar to use", max_length=200)),
                ('guest_info', models.TextField(blank=True, help_text='Extra info about the guest (background, topic, etc.) that the avatar should know')),
                ('welcome_message', models.TextField(blank=True, help_text='Custom welcome message to play when the guest enters the avatar room')),
                ('model_name', models.CharField(default='llama3.2:1b', help_text='Ollama model to use (e.g., llama3.2:1b, llama3.1:8b)', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Response creativity (0.0 = deterministic, 1.0 = creative)')),
                ('max_tokens', models.IntegerField(default=256, help_text='Maximum tokens per response')),
                ('piper_voice', models.CharField(default='en_US-lessac-medium', help_text='Piper TTS voice model', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this avatar prompt configuration')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority prompts are used first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, help_text='Optional: Link to a specific guest user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_prompts', to='auth.user')),
                ('show', models.ForeignKey(blank=True, help_text='Optional: Link to a specific show', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_prompts', to='members.show')),
            ],
            options={
                'verbose_name': 'Green Room Avatar Prompt',
                'verbose_name_plural': 'Green Room Avatar Prompts',
                'ordering': ['-priority', '-updated_at'],
                'indexes': [models.Index(fields=['show', 'is_active'], name='members_gre_show_id_1f8373_idx'), models.Index(fields=['guest', 'is_active'], name='members_gre_guest_i_c80e81_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuestConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text="The guest's display name", max_length=200)),
                ('guest_email', models.EmailField(blank=True, help_text="The guest's email (for identification)", max_length=254)),
                ('room_name', models.CharField(blank=True, help_text='LiveKit room name used for this session', max_length=200)),
                ('messages', models.JSONField(blank=True, default=list, help_text='Array of message objects: [{role, content, timestamp}]')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('message_count', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0, help_text='How long the conversation lasted')),
                ('guest_ready', models.BooleanField(default=False, help_text='Guest indicated they are ready to proceed')),
                ('guest_notes', models.TextField(blank=True, help_text='Admin notes about this guest from the conversation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, help_text='The guest user (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_conversations', to='auth.user')),
                ('prompt_used', models.ForeignKey(blank=True, help_text='Which prompt configuration was used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.greenroomprompt')),
                ('show', models.ForeignKey(blank=True, help_text='The show this conversation is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_conversations', to='members.show')),
            ],
            options={
                'verbose_name': 'Guest Avatar Conversation',
                'verbose_name_plural': 'Guest Avatar Conversations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['guest', '-updated_at'], name='members_gue_guest_i_f85cb5_idx'), models.Index(fields=['show', '-updated_at'], name='members_gue_show_id_cce7a5_idx'), models.Index(fields=['session_id'], name='members_gue_session_995612_idx')],
            },
        ),
    ]
