# Generated by Django 5.0.14 on 2026-07-18 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_avatar_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Email address for the account', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('coach', 'Coach')], default='athlete', help_text='Whether you are an athlete or coach', max_length=10)),
                ('school_or_organization', models.CharField(blank=True, help_text='Your school, club, or organization name', max_length=200)),
                ('position_or_sport', models.CharField(blank=True, help_text='Your sport, position, or coaching specialty', max_length=100)),
                ('message', models.TextField(blank=True, help_text="Tell us a bit about yourself and why you'd like to join")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='greenroomprompt',
            new_name='members_gre_show_id_763867_idx',
            old_name='members_gre_show_id_1f8373_idx',
        ),
        migrations.RenameIndex(
            model_name='greenroomprompt',
            new_name='members_gre_guest_i_a3bdd8_idx',
            old_name='members_gre_guest_i_c80e81_idx',
        ),
        migrations.RenameIndex(
            model_name='guestconversation',
            new_name='members_gue_guest_i_0953fe_idx',
            old_name='members_gue_guest_i_f85cb5_idx',
        ),
        migrations.RenameIndex(
            model_name='guestconversation',
            new_name='members_gue_show_id_582d4b_idx',
            old_name='members_gue_show_id_cce7a5_idx',
        ),
        migrations.RenameIndex(
            model_name='guestconversation',
            new_name='members_gue_session_834e36_idx',
            old_name='members_gue_session_995612_idx',
        ),
        migrations.AlterField(
            model_name='guestconversation',
            name='guest_ready',
            field=models.BooleanField(default=False, help_text="Guest indicated they're ready to proceed"),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
