# Generated by Django 5.0.14 on 2026-07-18 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_fix_missing_joinrequest_and_liveverif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guestconversation',
            name='auto_summary',
            field=models.TextField(blank=True, help_text='Auto-generated 2-3 sentence summary of this conversation (generated at session end)'),
        ),
        migrations.AddIndex(
            model_name='guestconversation',
            index=models.Index(fields=['ended_at'], name='members_gue_ended_a_5b4a3c_idx'),
        ),
    ]
