# Generated by Django 5.0.14 on 2026-07-18 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_guestconversation_auto_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChatFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question (used for matching)', max_length=500, unique=True)),
                ('answer', models.TextField(help_text='The answer to display')),
                ('keywords', models.CharField(blank=True, default='', help_text="Comma-separated keywords for basic matching (e.g. 'guest, become guest, sign up')", max_length=500)),
                ('category', models.CharField(blank=True, default='', help_text="Category like 'Guest Info', 'Privacy', 'Technical', 'Parent', 'General'", max_length=100)),
                ('is_published', models.BooleanField(default=True, help_text="Unpublished FAQs won't appear in exact matches")),
                ('priority', models.IntegerField(default=0, help_text='Higher = shown first in FAQ list')),
                ('times_asked', models.IntegerField(default=0, help_text='How many times this FAQ has been matched')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority', 'category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default="Lil' Dawg", help_text='Name of the chat assistant', max_length=100)),
                ('mood', models.CharField(choices=[('friendly', 'Friendly 🤗'), ('professional', 'Professional 🎙️'), ('enthusiastic', 'Enthusiastic ⚡'), ('calm', 'Calm 🧘'), ('coach', 'Coach 🏆')], default='friendly', help_text='Overall mood/personality of the assistant', max_length=20)),
                ('tone', models.CharField(choices=[('warm', 'Warm'), ('formal', 'Formal'), ('conversational', 'Conversational'), ('excited', 'Excited')], default='conversational', help_text='Communication tone', max_length=20)),
                ('system_prompt', models.TextField(default="You are a helpful assistant for 'IN the GAME with DOC' — a sports broadcast platform. You answer questions about becoming a guest, watching live shows, joining as a parent, data security, privacy, and general use of the platform at yourdomain.com. Be concise (2-3 sentences). If you don't know, say so.", help_text='Base system prompt for the Ollama model')),
                ('restricted_topics', models.TextField(blank=True, default='', help_text="Comma-separated topics the assistant should NOT discuss (e.g. 'politics, religion, NSFW')")),
                ('max_tokens', models.IntegerField(default=150, help_text='Maximum tokens per response (keep low for 1B model)')),
                ('temperature', models.FloatField(default=0.7, help_text='Model temperature (0.0 = deterministic, 1.0 = creative)')),
                ('prefer_faq_exact', models.BooleanField(default=True, help_text='If enabled, always serve exact FAQ matches (no model inference)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Config',
                'verbose_name_plural': 'Chat Config',
            },
        ),
        migrations.CreateModel(
            name='SiteChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('messages', models.JSONField(default=list, help_text='List of {role, content} messages')),
                ('message_count', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteChatUnanswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The unanswered question')),
                ('answer_given', models.TextField(blank=True, default='', help_text='What the model answered (if anything)')),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.sitechatsession')),
            ],
            options={
                'verbose_name': 'Unanswered Question',
                'verbose_name_plural': 'Unanswered Questions',
                'ordering': ['-asked_at'],
            },
        ),
    ]
