# Generated by Django 5.0.14 on 2026-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_sitechatfaq_sitechatconfig_sitechatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitechatconfig',
            name='business_hours',
            field=models.CharField(blank=True, default='', help_text='Optional: Business hours shown to visitors', max_length=200),
        ),
        migrations.AddField(
            model_name='sitechatconfig',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Business contact email shown to visitors (e.g. doc@yourdomain.com)', max_length=254),
        ),
        migrations.AddField(
            model_name='sitechatconfig',
            name='contact_form_url',
            field=models.CharField(blank=True, default='', help_text='URL to the contact form page (e.g. /contact)', max_length=300),
        ),
        migrations.AddField(
            model_name='sitechatconfig',
            name='social_links',
            field=models.TextField(blank=True, default='', help_text="Optional: Comma-separated social media links (e.g. 'Twitter: https://twitter.com/doc, YouTube: https://youtube.com/@doc')"),
        ),
        migrations.AddField(
            model_name='sitechatconfig',
            name='video_submission_info',
            field=models.TextField(blank=True, default='', help_text='Instructions for guests on how/where to submit videos or media. This is injected into the system prompt so the model can answer accurately.'),
        ),
    ]
