# Generated by Django 5.0.14 on 2026-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_sitechatconfig_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitechatconfig',
            name='rate_limit_block_minutes',
            field=models.IntegerField(default=5, help_text='Minutes to block IP after exceeding limit'),
        ),
        migrations.AddField(
            model_name='sitechatconfig',
            name='rate_limit_per_minute',
            field=models.IntegerField(default=10, help_text='Max chat requests per IP per minute'),
        ),
    ]
